In [1]:
import pandas as pd
from datetime import datetime

In [22]:
#### THIS IS THE ONLY CELL CONTAINING ELEMENTS THAT NEED TO BE CHANGED
    # 1) the directory and Excel sheet number containing underway IFCB log data
    # 2) the directory and Excel sheet number containing discrete IFCB log data
    # 3) the cruise name/number (format example: AR82)
    # 4) the ifcb instrument number used for OOI discrete and underway sampling (format example: AR82)
        # this notebook is written assuming one instrument is used for both IFCB sampling sampling types
    # The directory containing either 5) seperate or 6) merged bottle files from the cruise

# Read in and standardize Underway IFCB data
processed_underway_ifcb_data = pd.read_excel('IFCB_Logs/Pioneer-22_AR98_IFCB_Log_2026-03-19_Ver_1-00.xlsx', sheet_name=0, header=3)   # change me (1)
processed_underway_ifcb_data = processed_underway_ifcb_data.fillna('')
processed_underway_ifcb_data.columns = processed_underway_ifcb_data.columns.str.strip()


# Read in and standardize Discrete IFCB data
processed_discrete_ifcb_data = pd.read_excel('IFCB_Logs/Pioneer-22_AR98_IFCB_Log_2026-03-19_Ver_1-00.xlsx', sheet_name=1, header=3)  # change me (2)
processed_discrete_ifcb_data = processed_discrete_ifcb_data.fillna('')
processed_discrete_ifcb_data.columns = processed_discrete_ifcb_data.columns.str.strip()

cruise = 'AR98'  # change me (3)
ifcb_instrument_num = 'IFCB199'  # change me (4)

# Read in the bottle files (the datetimes from here are needed for discrete samples)
    # (It's easier to complete steps related to bottle file processesing after the cruise/after ship data recovery)
# Define the folder with your .bl files
bottle_folder_path = 'Bottle_Data/'   # change me (5)
# Or the merged bottle file 
merged_bottle_file = pd.read_csv('Bottle_Data/Pioneer-22_AR98A_CTD_Bottle_Data_2025-12-18_ACR.csv')    # change me (6)

In [23]:
processed_discrete_ifcb_data.columns

Index(['Filename', 'HDR Comment', 'Sample Type', 'Cruise Leg', 'Site', 'Cast',
       'Niskin', 'IFCB Bottle', 'Target Cast Depth', 'Trip Depth',
       '# Triggers', '# ROIs', 'Run Time', 'Inhibit Time', 'Sample Time',
       'Volume Analyzed', 'ROIs/ml', 'Cast Start Latitude',
       'Cast Start Longitude', 'Notes'],
      dtype='object')

In [24]:
# Ensure Cast and Bottle numbers in the Discrete data df are interpreted as ints and preview the data

processed_discrete_ifcb_data['Cast'] = pd.to_numeric(processed_discrete_ifcb_data['Cast'], errors='coerce')
processed_discrete_ifcb_data['Niskin'] = pd.to_numeric(processed_discrete_ifcb_data['Niskin'], errors='coerce')
processed_discrete_ifcb_data = processed_discrete_ifcb_data.dropna(subset=['Cast', 'Niskin'])
processed_discrete_ifcb_data['Cast'] = processed_discrete_ifcb_data['Cast'].astype(int)
processed_discrete_ifcb_data['Niskin'] = processed_discrete_ifcb_data['Niskin'].astype(int)


processed_discrete_ifcb_data

,Filename,HDR Comment,Sample Type,Cruise Leg,Site,Cast,Niskin,IFCB Bottle,Target Cast Depth,Trip Depth,# Triggers,# ROIs,Run Time,Inhibit Time,Sample Time,Volume Analyzed,ROIs/ml,Cast Start Latitude,Cast Start Longitude,Notes
0,D20251101T164030_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,1,6,2,7,7.3,3698,3381,1200.866944,306.844688,894.022257,3.725093,907.628410,35.949567,-75.126083,LTER IFCB
1,D20251101T170419_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,1,6,2,7,7.3,3631,3309,1200.964583,300.425556,900.539028,3.752246,881.871830,35.949567,-75.126083,LTER IFCB
2,D20251101T172810_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,1,6,2,7,7.3,3705,3396,1201.778889,306.580000,895.198889,3.729995,910.456894,35.949567,-75.126083,LTER IFCB
3,D20251101T180159_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,1,2,11,bottom,27.0,3419,3144,1200.889583,283.876562,917.013021,3.820888,822.845459,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample
4,D20251101T183013_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,1,2,11,bottom,27.0,3422,3090,1200.994167,284.636094,916.358073,3.818159,809.290628,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,D20251116T014257_IFCB199,ar98b_c4n5_b2_cn_7m,discrete_water_sample,b,CP12CNSW,4,5,2,7,7.4,2496,2479,1200.884444,207.981337,992.903108,4.137096,599.212547,35.949933,-75.128200,
82,D20251116T020646_IFCB199,ar98b_c4n5_b2_cn_7m,discrete_water_sample,b,CP12CNSW,4,5,2,7,7.4,2434,2408,1200.947917,202.684010,998.263906,4.159433,578.925068,35.949933,-75.128200,
83,D20251116T023347_IFCB199,ar98b_c4n1_b1_cn_bottom,discrete_water_sample,b,CP12CNSW,4,1,1,bottom,27.3,1998,1972,1200.907917,166.444097,1034.463819,4.310266,457.512376,35.949933,-75.128200,
84,D20251116T025737_IFCB199,ar98b_c4n1_b1_cn_bottom,discrete_water_sample,b,CP12CNSW,4,1,1,bottom,27.3,1977,1933,1200.916111,164.649861,1036.266250,4.317776,447.684174,35.949933,-75.128200,
85,D20251116T032126_IFCB199,ar98b_c4n1_b1_cn_bottom,discrete_water_sample,b,CP12CNSW,4,1,1,bottom,27.3,1946,1908,1200.944861,162.020920,1038.923941,4.328850,440.763738,35.949933,-75.128200,

In [25]:
# Preview the Underway data

processed_underway_ifcb_data

,Filename,HDR Comment,Site,Intake Pump,# Triggers,# ROIs,Run Time,Inhibit Time,Sample Time,Volume Analyzed,ROIs/ml,Ship Latitude,Ship Longitude,Notes
0,D20251030T170909_IFCB199,ar98a_underway,,R/V Armstrong diaphragm pump,5284,4713,1201.528611,439.009687,762.518924,3.177162,1483.399251,41.210,-71.233,
1,D20251030T173245_IFCB199,ar98a_underway,,R/V Armstrong diaphragm pump,4154,3664,1201.593611,344.458160,857.135451,3.571398,1025.928864,41.158,-71.298,
2,D20251030T175621_IFCB199,ar98a_underway,,R/V Armstrong diaphragm pump,3673,3248,1201.048889,305.949236,895.099653,3.729582,870.875100,41.104,-71.367,
3,D20251030T181956_IFCB199,ar98a_underway,,R/V Armstrong diaphragm pump,3214,2846,1201.006250,267.862569,933.143681,3.888099,731.977309,41.050,-71.436,
4,D20251030T184331_IFCB199,ar98a_underway,,R/V Armstrong diaphragm pump,2916,2622,1200.907222,243.616736,957.290486,3.988710,657.355326,40.999,-71.502,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,D20251119T091627_IFCB199,ar98b_underway,,R/V Armstrong diaphragm pump,6994,6989,1201.314306,582.004375,619.309931,2.580458,2708.433883,41.114,-70.893,
985,D20251119T094017_IFCB199,ar98b_underway,,R/V Armstrong diaphragm pump,6489,6363,1201.755000,540.033715,661.721285,2.757172,2307.799424,41.175,-70.883,
986,D20251119T100408_IFCB199,ar98b_underway,,R/V Armstrong diaphragm pump,6356,6221,1200.895278,530.149514,670.745764,2.794774,2225.940260,41.230,-70.886,
987,D20251119T102758_IFCB199,ar98b_underway,,R/V Armstrong diaphragm pump,6426,6337,1200.885139,535.086285,665.798854,2.774162,2284.293508,41.274,-70.889,
988,D20251119T111031_IFCB199,ar98b_underway,,R/V Armstrong diaphragm pump,6747,6460,1201.642917,561.250694,640.392222,2.668301,2421.016287,41.356,-70.894,

In [7]:
# Get datetimes from bottle data files

"""# Get list of all .bl files
bl_files = [os.path.join(bottle_folder_path, f) for f in os.listdir(bottle_folder_path) if f.lower().endswith('.bl')]

# Initialize list to store all rows
all_bottle_data = []

for filepath in bl_files:
    filename = os.path.basename(filepath)
    
    # Extract cruise and cast from the filename
    try:
        cruise_portion = filename.split('_')[0]      # e.g., 'ar87a'
        cast_portion = filename.split('_')[1].split('.')[0]  # e.g., '023'
    except IndexError:
        print(f"Filename format unexpected: {filename}")
        continue

    with open(filepath, 'r') as file:
        lines = file.readlines()
    
    for line in lines:
        line = line.strip()
        
        # Skip lines that don't start with data (e.g., path or RESET lines)
        if not line or not line[0].isdigit():
            continue
        
        parts = [p.strip() for p in line.split(',')]
        if len(parts) != 5:
            continue  # Skip malformed lines

        try:
            niskin = int(parts[0])
            bottle = int(parts[1])
            dt_str = parts[2]
            start_byte = int(parts[3])
            end_byte = int(parts[4])

            # Convert to datetime
            dt = datetime.strptime(dt_str, '%b %d %Y %H:%M:%S')
            
            all_bottle_data.append({
                'cruise': cruise_portion,
                'Cast': cast_portion,
                'Niskin': niskin,
                'bottle': bottle,
                'date': dt.date(),
                'time': dt.time(),
                'datetime': dt,
                'start_byte': start_byte,
                'end_byte': end_byte,
                'source_file': filename
            })
        except Exception as e:
            print(f"Error parsing line in {filename}: {line} — {e}")

# Create DataFrame
df = pd.DataFrame(all_bottle_data)

# Preview result
print(f"Parsed {len(df)} rows from {len(bl_files)} files.")
df.head()

output_path = f'./Bottle_file_copies/merged_bottle_data_csvs/{cruise}_merged_bottle_data.csv'
df.to_csv(output_path, index=False)

print(f"DataFrame saved to {output_path}")"""

# Or read in and look at the merged bottle file directly
#merged_bottle_file.columns.tolist()
merged_bottle_file.head()

,Cast,Bottle Position,Start Time [UTC],Start Longitude [degrees],Start Latitude [degrees],Filename,Date Time,"Pressure, Digiquartz [db]","Depth [salt water, m]",Latitude [deg],...,"Conductivity, 2 [S/m]","Salinity, Practical [PSU]","Salinity, Practical, 2 [PSU]","Oxygen raw, SBE 43 [V]","Oxygen, SBE 43 [ml/l]","Oxygen Saturation, Garcia & Gordon [ml/l]","Beam Attenuation, WET Labs C-Star [1/m]","Beam Transmission, WET Labs C-Star [%]","Fluorescence, WET Labs ECO-AFL/FL [mg/m^3]",Cruise
0,1,1,2025-11-01T13:16:10.000Z,-75.126,35.9495,ar98a_001.hex,2025-11-01T13:19:22.000Z,27.506,27.303,35.94956,...,4.422975,33.3659,33.3639,2.6526,5.0377,5.39850,0.3969,90.5543,0.7093 (avg),AR98A
1,1,2,2025-11-01T13:16:10.000Z,-75.126,35.9495,ar98a_001.hex,2025-11-01T13:19:52.000Z,27.519,27.316,35.94956,...,4.422903,33.3659,33.3642,2.6272,4.9617,5.39858,0.3963,90.5682,0.7562 (avg),AR98A
2,1,3,2025-11-01T13:16:10.000Z,-75.126,35.9495,ar98a_001.hex,2025-11-01T13:23:05.000Z,20.235,20.086,35.94958,...,4.422676,33.3651,33.3642,2.6433,5.0077,5.39845,0.3931,90.6391,0.7613 (avg),AR98A
3,1,4,2025-11-01T13:16:10.000Z,-75.126,35.9495,ar98a_001.hex,2025-11-01T13:23:30.000Z,20.544,20.393,35.94958,...,4.422556,33.3644,33.3642,2.6360,4.9850,5.39873,0.3981,90.5263,0.7490 (avg),AR98A
4,1,5,2025-11-01T13:16:10.000Z,-75.126,35.9495,ar98a_001.hex,2025-11-01T13:26:33.000Z,7.306,7.252,35.94957,...,4.422333,33.3648,33.3658,2.6688,5.0659,5.39861,0.3907,90.6942,0.7296 (avg),AR98A

In [26]:
processed_discrete_ifcb_data.head()

,Filename,HDR Comment,Sample Type,Cruise Leg,Site,Cast,Niskin,IFCB Bottle,Target Cast Depth,Trip Depth,# Triggers,# ROIs,Run Time,Inhibit Time,Sample Time,Volume Analyzed,ROIs/ml,Cast Start Latitude,Cast Start Longitude,Notes
0,D20251101T164030_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,1,6,2,7,7.3,3698,3381,1200.866944,306.844688,894.022257,3.725093,907.628410,35.949567,-75.126083,LTER IFCB
1,D20251101T170419_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,1,6,2,7,7.3,3631,3309,1200.964583,300.425556,900.539028,3.752246,881.871830,35.949567,-75.126083,LTER IFCB
2,D20251101T172810_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,1,6,2,7,7.3,3705,3396,1201.778889,306.580000,895.198889,3.729995,910.456894,35.949567,-75.126083,LTER IFCB
3,D20251101T180159_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,1,2,11,bottom,27.0,3419,3144,1200.889583,283.876562,917.013021,3.820888,822.845459,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample
4,D20251101T183013_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,1,2,11,bottom,27.0,3422,3090,1200.994167,284.636094,916.358073,3.818159,809.290628,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample

In [28]:
# Make sure both are strings and pad the processed_discrete_ifcb_data to match the 3-digit format in df
processed_discrete_ifcb_data['Cast'] = processed_discrete_ifcb_data['Cast'].astype(str).str.zfill(3)
processed_discrete_ifcb_data['Cruise Leg'] = processed_discrete_ifcb_data['Cruise Leg'].str.lower()

merged_bottle_file['Cast'] = merged_bottle_file['Cast'].astype(str).str.zfill(3)  # Just to be safe
# Parse out leg from cruise number
merged_bottle_file['Cruise Leg'] = merged_bottle_file['Cruise'].str.strip().str[-1]
merged_bottle_file['Cruise Leg'] = merged_bottle_file['Cruise Leg'].str.lower()

merged_bottle_file = merged_bottle_file.rename(columns={'Bottle Position': 'Niskin'})

# Now merge
merged = processed_discrete_ifcb_data.merge(
    merged_bottle_file[['Cruise Leg', 'Cast', 'Niskin', 'Date Time', 'Depth [salt water, m]']],
    on=['Cruise Leg', 'Cast', 'Niskin'],
    how='left'
)

# Rename cols for clarity
merged = merged.rename(columns={'Date Time': 'bottle_datetime'})
merged = merged.rename(columns={'Depth [salt water, m]': 'bottle_depth'})


# Preview
merged.head()
#merged_bottle_file.head()

,Filename,HDR Comment,Sample Type,Cruise Leg,Site,Cast,Niskin,IFCB Bottle,Target Cast Depth,Trip Depth,...,Run Time,Inhibit Time,Sample Time,Volume Analyzed,ROIs/ml,Cast Start Latitude,Cast Start Longitude,Notes,bottle_datetime,bottle_depth
0,D20251101T164030_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,001,6,2,7,7.3,...,1200.866944,306.844688,894.022257,3.725093,907.628410,35.949567,-75.126083,LTER IFCB,2025-11-01T13:27:01.000Z,7.416
1,D20251101T170419_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,001,6,2,7,7.3,...,1200.964583,300.425556,900.539028,3.752246,881.871830,35.949567,-75.126083,LTER IFCB,2025-11-01T13:27:01.000Z,7.416
2,D20251101T172810_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,001,6,2,7,7.3,...,1201.778889,306.580000,895.198889,3.729995,910.456894,35.949567,-75.126083,LTER IFCB,2025-11-01T13:27:01.000Z,7.416
3,D20251101T180159_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,001,2,11,bottom,27.0,...,1200.889583,283.876562,917.013021,3.820888,822.845459,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample,2025-11-01T13:19:52.000Z,27.316
4,D20251101T183013_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,001,2,11,bottom,27.0,...,1200.994167,284.636094,916.358073,3.818159,809.290628,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample,2025-11-01T13:19:52.000Z,27.316

In [29]:
processed_discrete_ifcb_data_merged = merged
processed_discrete_ifcb_data_merged

,Filename,HDR Comment,Sample Type,Cruise Leg,Site,Cast,Niskin,IFCB Bottle,Target Cast Depth,Trip Depth,...,Run Time,Inhibit Time,Sample Time,Volume Analyzed,ROIs/ml,Cast Start Latitude,Cast Start Longitude,Notes,bottle_datetime,bottle_depth
0,D20251101T164030_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,001,6,2,7,7.3,...,1200.866944,306.844688,894.022257,3.725093,907.628410,35.949567,-75.126083,LTER IFCB,2025-11-01T13:27:01.000Z,7.416
1,D20251101T170419_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,001,6,2,7,7.3,...,1200.964583,300.425556,900.539028,3.752246,881.871830,35.949567,-75.126083,LTER IFCB,2025-11-01T13:27:01.000Z,7.416
2,D20251101T172810_IFCB199,ar98a_c1n6_b2_cn_7m,discrete_water_sample,a,CP10CNSM,001,6,2,7,7.3,...,1201.778889,306.580000,895.198889,3.729995,910.456894,35.949567,-75.126083,LTER IFCB,2025-11-01T13:27:01.000Z,7.416
3,D20251101T180159_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,001,2,11,bottom,27.0,...,1200.889583,283.876562,917.013021,3.820888,822.845459,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample,2025-11-01T13:19:52.000Z,27.316
4,D20251101T183013_IFCB199,ar98a_c1n2_b11_cn_bottom,discrete_water_sample,a,CP10CNSM,001,2,11,bottom,27.0,...,1200.994167,284.636094,916.358073,3.818159,809.290628,35.949567,-75.126083,LTER IFCB; IFCB bottle 11 was LTER IFCB sample,2025-11-01T13:19:52.000Z,27.316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,D20251116T014257_IFCB199,ar98b_c4n5_b2_cn_7m,discrete_water_sample,b,CP12CNSW,004,5,2,7,7.4,...,1200.884444,207.981337,992.903108,4.137096,599.212547,35.949933,-75.128200,,NaN,NaN
82,D20251116T020646_IFCB199,ar98b_c4n5_b2_cn_7m,discrete_water_sample,b,CP12CNSW,004,5,2,7,7.4,...,1200.947917,202.684010,998.263906,4.159433,578.925068,35.949933,-75.128200,,NaN,NaN
83,D20251116T023347_IFCB199,ar98b_c4n1_b1_cn_bottom,discrete_water_sample,b,CP12CNSW,004,1,1,bottom,27.3,...,1200.907917,166.444097,1034.463819,4.310266,457.512376,35.949933,-75.128200,,NaN,NaN
84,D20251116T025737_IFCB199,ar98b_c4n1_b1_cn_bottom,discrete_water_sample,b,CP12CNSW,004,1,1,bottom,27.3,...,1200.916111,164.649861,1036.266250,4.317776,447.684174,35.949933,-75.128200,,NaN,NaN
85,D20251116T032126_IFCB199,ar98b_c4n1_b1_cn_bottom,discrete_water_sample,b,CP12CNSW,004,1,1,bottom,27.3,...,1200.944861,162.020920,1038.923941,4.328850,440.763738,35.949933,-75.128200,,NaN,NaN

In [33]:
# handling samples associated with 2 differing sites for underway data

def parse_sites(site_val):
    if pd.isna(site_val) or site_val == '':
        return '', ''
    
    # split on semicolon and clean whitespace
    sites = [s.strip() for s in str(site_val).split(';') if s.strip() != '']
    
    # format as site_*
    sites = ['site_' + s for s in sites]
    
    # assign to tag1 and tag3
    tag1 = sites[0] if len(sites) >= 1 else ''
    tag3 = sites[1] if len(sites) >= 2 else ''
    
    return tag1, tag3

site_tags = processed_underway_ifcb_data['Site'].apply(parse_sites)

0      (, )
1      (, )
2      (, )
3      (, )
4      (, )
       ...
984    (, )
985    (, )
986    (, )
987    (, )
988    (, )
Name: Site, Length: 989, dtype: object

In [60]:
# handling qc tags

def get_qc_tags(row):
    qc_tags = []

    sample_type = str(row.get('Sample Type', '')).lower() if pd.notna(row.get('Sample Type', '')) else ''
    hdr_comment = str(row.get('HDR Comment', '')).lower() if pd.notna(row.get('HDR Comment', '')) else ''
    notes = str(row.get('Notes', '')).lower() if pd.notna(row.get('Notes', '')) else ''

    # Existing QC logic
    if 'test' in sample_type or 'test' in hdr_comment:
        qc_tags.append('qc_test')
    if 'beads' in sample_type or 'beads' in hdr_comment:
        qc_tags.append('qc_beads')

    # Notes-based QC logic
    if 'focus' in notes:
        qc_tags.append('qc_bad_focus')
    # Handle debubble BEFORE bubble to avoid substring conflicts
    if 'debubble' in notes or 'debubbled' in notes:
        qc_tags.append('qc_ifcb_debubbled')
    elif 'bubble' in notes or 'bubbles' in notes:
        qc_tags.append('qc_bubbles_in_ROIs')
    if 'stopped' in notes or 'stopped_early' in notes:
        qc_tags.append('qc_stopped_early')
    if 'bad_data' in notes:
        qc_tags.append('qc_bad_data')

    # remove duplicates while preserving order
    qc_tags = list(dict.fromkeys(qc_tags))

    return qc_tags

In [61]:
columns_in_metadata_csv = ['filename', 'Latitude', 'Longitude', 'Depth', 'sample_type', 'Cruise', 'Instrument', 'datetime', 'tag1', 'tag2', 'tag3']

# Parse site tags for underway
site_tags_underway = processed_underway_ifcb_data['Site'].apply(parse_sites)

processed_underway_ifcb_data_mapped = {
    'filename': processed_underway_ifcb_data['Filename'], 
    'Latitude': processed_underway_ifcb_data['Ship Latitude'],
    'Longitude': processed_underway_ifcb_data['Ship Longitude'],
    'Depth': 2.13, #for R/V Armstrong Aft Diaphram Pump
    'sample_type': 'underway',
    'Cruise': cruise,
    'Instrument': ifcb_instrument_num,
    'datetime': '',
    #'tag1': processed_underway_ifcb_data['Site'].apply(lambda x: 'site_' + str(x) if pd.notna(x) and x != '' else x), 
    'tag1': site_tags.apply(lambda x: x[0]),
    'tag2': 'targetdepth_surface',
    'tag3': site_tags.apply(lambda x: x[1])
}

processed_discrete_ifcb_data_mapped = {
    'filename': processed_discrete_ifcb_data_merged['Filename'], 
    'Latitude': processed_discrete_ifcb_data_merged['Cast Start Latitude'],
    'Longitude': processed_discrete_ifcb_data_merged['Cast Start Longitude'],
    'Depth': processed_discrete_ifcb_data_merged['bottle_depth'],
    'sample_type': processed_discrete_ifcb_data_merged['Sample Type'].apply(
        lambda x: 'discrete' if 'discrete' in str(x).lower() and 'test' not in str(x).lower() and 'beads' not in str(x).lower() else x
    ),
    'Cruise': cruise,
    'Instrument':ifcb_instrument_num,
    'datetime': processed_discrete_ifcb_data_merged['bottle_datetime'],
    'tag1': processed_discrete_ifcb_data_merged['Site'].apply(lambda x: 'site_' + str(x) if pd.notna(x) and x != '' else x), 
    'tag2': processed_discrete_ifcb_data_merged['Target Cast Depth'].apply(lambda x: 'targetdepth_' + str(x) if pd.notna(x) and x != '' else x), 
    'tag3': ''
}

# Generate QC tags lists
qc_tag_lists_underway = processed_underway_ifcb_data.apply(get_qc_tags, axis=1)
qc_tag_lists_discrete = processed_discrete_ifcb_data_merged.apply(get_qc_tags, axis=1)

# Find max QC tag counts
max_qc_tags_underway = qc_tag_lists_underway.apply(len).max()
max_qc_tags_discrete = qc_tag_lists_discrete.apply(len).max()

# Add tag4, tag5, ... as needed for underway
for i in range(max_qc_tags_underway):
    processed_underway_ifcb_data_mapped[f'tag{i+4}'] = qc_tag_lists_underway.apply(
        lambda tags: tags[i] if i < len(tags) else ''
    )

# Add tag4, tag5, ... as needed for discrete
for i in range(max_qc_tags_discrete):
    processed_discrete_ifcb_data_mapped[f'tag{i+4}'] = qc_tag_lists_discrete.apply(
        lambda tags: tags[i] if i < len(tags) else ''
    )

# Convert to DataFrames
underway_new = pd.DataFrame(processed_underway_ifcb_data_mapped).fillna('')
discrete_new = pd.DataFrame(processed_discrete_ifcb_data_mapped).fillna('')

# Combine
metadata_df = pd.concat([underway_new, discrete_new], ignore_index=True).fillna('')

pd.set_option('display.max_rows', None)
metadata_df

,filename,Latitude,Longitude,Depth,sample_type,Cruise,Instrument,datetime,tag1,tag2,tag3,tag4,tag5,tag6
0,D20251030T170909_IFCB199,41.210000,-71.233000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
1,D20251030T173245_IFCB199,41.158000,-71.298000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
2,D20251030T175621_IFCB199,41.104000,-71.367000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
3,D20251030T181956_IFCB199,41.050000,-71.436000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
4,D20251030T184331_IFCB199,40.999000,-71.502000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
5,D20251030T190706_IFCB199,40.951000,-71.577000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
6,D20251030T193041_IFCB199,40.908000,-71.654000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
7,D20251030T195417_IFCB199,40.864000,-71.734000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
8,D20251030T201752_IFCB199,40.818000,-71.812000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
9,D20251030T204127_IFCB199,40.775000,-71.888000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
10,D20251030T210502_IFCB199,40.730000,-71.967000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
11,D20251030T212837_IFCB199,40.687000,-72.041000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
12,D20251030T215212_IFCB199,40.643000,-72.119000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
13,D20251030T221548_IFCB199,40.602000,-72.194000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
14,D20251031T002220_IFCB199,40.382000,-72.600000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,qc_ifcb_debubbled,,
15,D20251031T003410_IFCB199,40.363000,-72.636000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
16,D20251031T005800_IFCB199,40.358000,-72.628000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
17,D20251031T012150_IFCB199,40.354000,-72.616000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
18,D20251031T014540_IFCB199,40.327000,-72.672000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
19,D20251031T020930_IFCB199,40.292000,-72.757000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
20,D20251031T023319_IFCB199,40.252000,-72.838000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
21,D20251031T025708_IFCB199,40.211000,-72.918000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
22,D20251031T032057_IFCB199,40.168000,-72.997000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
23,D20251031T034446_IFCB199,40.128000,-73.068000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
24,D20251031T040836_IFCB199,40.088000,-73.142000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
25,D20251031T043225_IFCB199,40.048000,-73.216000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
26,D20251031T045614_IFCB199,40.007000,-73.289000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
27,D20251031T052003_IFCB199,39.967000,-73.359000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
28,D20251031T054353_IFCB199,39.927000,-73.429000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
29,D20251031T060743_IFCB199,39.889000,-73.496000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
30,D20251031T063134_IFCB199,39.842000,-73.544000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
31,D20251031T065524_IFCB199,39.792000,-73.590000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
32,D20251031T071914_IFCB199,39.741000,-73.634000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
33,D20251031T074304_IFCB199,39.693000,-73.686000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
34,D20251031T080655_IFCB199,39.645000,-73.736000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
35,D20251031T083045_IFCB199,39.598000,-73.783000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
36,D20251031T085435_IFCB199,39.549000,-73.830000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
37,D20251031T091825_IFCB199,39.500000,-73.876000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
38,D20251031T094214_IFCB199,39.450000,-73.922000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
39,D20251031T100605_IFCB199,39.400000,-73.967000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
40,D20251031T102955_IFCB199,39.350000,-74.011000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
41,D20251031T105345_IFCB199,39.302000,-74.054000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
42,D20251031T111735_IFCB199,39.252000,-74.097000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
43,D20251031T114125_IFCB199,39.202000,-74.140000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
44,D20251031T122359_IFCB199,39.113000,-74.216000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
45,D20251031T124749_IFCB199,39.065000,-74.259000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
46,D20251031T132432_IFCB199,38.989000,-74.326000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
47,D20251031T134822_IFCB199,38.937000,-74.363000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
48,D20251031T141212_IFCB199,38.882000,-74.392000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,qc_stopped_early,,
49,D20251031T142958_IFCB199,38.840000,-74.413000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
50,D20251031T145348_IFCB199,38.787000,-74.442000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
51,D20251031T151738_IFCB199,38.732000,-74.472000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
52,D20251031T154129_IFCB199,38.675000,-74.502000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
53,D20251031T160519_IFCB199,38.619000,-74.533000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
54,D20251031T162909_IFCB199,38.565000,-74.568000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
55,D20251031T165259_IFCB199,38.513000,-74.605000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
56,D20251031T171649_IFCB199,38.463000,-74.640000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
57,D20251031T174040_IFCB199,38.409000,-74.673000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
58,D20251031T180430_IFCB199,38.349000,-74.690000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
59,D20251031T182820_IFCB199,38.291000,-74.706000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,qc_stopped_early,,
60,D20251031T184518_IFCB199,38.251000,-74.720000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
61,D20251031T185653_IFCB199,38.225000,-74.736000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
62,D20251031T190829_IFCB199,38.201000,-74.751000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
63,D20251031T192004_IFCB199,38.174000,-74.766000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
64,D20251031T193139_IFCB199,38.149000,-74.780000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
65,D20251031T194314_IFCB199,38.122000,-74.795000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
66,D20251031T195449_IFCB199,38.098000,-74.809000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
67,D20251031T200624_IFCB199,38.072000,-74.824000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
68,D20251031T201759_IFCB199,38.045000,-74.838000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
69,D20251031T202934_IFCB199,38.021000,-74.851000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
70,D20251031T204109_IFCB199,37.994000,-74.865000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
71,D20251031T205245_IFCB199,37.969000,-74.878000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
72,D20251031T210420_IFCB199,37.942000,-74.891000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
73,D20251031T213439_IFCB199,37.873000,-74.926000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
74,D20251031T214614_IFCB199,37.845000,-74.940000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
75,D20251031T215749_IFCB199,37.820000,-74.953000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
76,D20251031T220924_IFCB199,37.792000,-74.969000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
77,D20251031T222059_IFCB199,37.765000,-74.984000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
78,D20251031T223234_IFCB199,37.740000,-74.998000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
79,D20251031T224409_IFCB199,37.712000,-75.014000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
80,D20251031T225544_IFCB199,37.687000,-75.029000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
81,D20251031T230719_IFCB199,37.659000,-75.045000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
82,D20251031T231855_IFCB199,37.631000,-75.062000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
83,D20251031T233030_IFCB199,37.605000,-75.077000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
84,D20251031T234205_IFCB199,37.576000,-75.093000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
85,D20251031T235340_IFCB199,37.550000,-75.109000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
86,D20251101T000515_IFCB199,37.521000,-75.126000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
87,D20251101T001650_IFCB199,37.492000,-75.142000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
88,D20251101T002825_IFCB199,37.464000,-75.157000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
89,D20251101T004000_IFCB199,37.435000,-75.173000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
90,D20251101T005135_IFCB199,37.409000,-75.190000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
91,D20251101T010310_IFCB199,37.383000,-75.213000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
92,D20251101T011446_IFCB199,37.358000,-75.234000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
93,D20251101T012621_IFCB199,37.331000,-75.255000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
94,D20251101T013756_IFCB199,37.305000,-75.277000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
95,D20251101T014931_IFCB199,37.280000,-75.297000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
96,D20251101T020106_IFCB199,37.253000,-75.319000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
97,D20251101T021241_IFCB199,37.228000,-75.339000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
98,D20251101T022416_IFCB199,37.201000,-75.361000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
99,D20251101T023551_IFCB199,37.174000,-75.384000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
100,D20251101T024727_IFCB199,37.149000,-75.404000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
101,D20251101T025902_IFCB199,37.120000,-75.425000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
102,D20251101T032920_IFCB199,37.048000,-75.475000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
103,D20251101T034055_IFCB199,37.019000,-75.494000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
104,D20251101T035231_IFCB199,36.991000,-75.508000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
105,D20251101T040406_IFCB199,36.957000,-75.510000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
106,D20251101T110740_IFCB199,35.954000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
107,D20251101T111930_IFCB199,35.953000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
108,D20251101T114319_IFCB199,35.953000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
109,D20251101T120708_IFCB199,35.953000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
110,D20251101T123059_IFCB199,35.953000,-75.123000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
111,D20251101T125449_IFCB199,35.954000,-75.126000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
112,D20251101T131839_IFCB199,35.950000,-75.126000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
113,D20251101T134228_IFCB199,35.950000,-75.129000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
114,D20251101T140618_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
115,D20251101T143008_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
116,D20251101T145358_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
117,D20251101T151728_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
118,D20251101T152458_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
119,D20251101T153228_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
120,D20251101T153958_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
121,D20251101T154728_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
122,D20251101T155458_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
123,D20251101T160228_IFCB199,35.951000,-75.131000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
124,D20251101T160958_IFCB199,35.951000,-75.132000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
125,D20251101T161728_IFCB199,35.951000,-75.132000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
126,D20251101T162458_IFCB199,35.951000,-75.132000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
127,D20251101T232600_IFCB199,36.169000,-74.708000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
128,D20251101T234950_IFCB199,36.169000,-74.708000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
129,D20251102T003222_IFCB199,36.171000,-74.724000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
130,D20251102T005612_IFCB199,36.176000,-74.795000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
131,D20251102T012002_IFCB199,36.178000,-74.823000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
132,D20251102T014351_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
133,D20251102T020741_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
134,D20251102T023132_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
135,D20251102T025521_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
136,D20251102T031910_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
137,D20251102T034300_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
138,D20251102T040650_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
139,D20251102T043040_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
140,D20251102T045429_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
141,D20251102T051818_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
142,D20251102T054207_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
143,D20251102T060556_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
144,D20251102T062947_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
145,D20251102T065337_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
146,D20251102T071726_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
147,D20251102T074116_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
148,D20251102T080505_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
149,D20251102T082855_IFCB199,36.179000,-74.827000,2.13,underway,AR98,IFCB199,,site_CP11NOSM,targetdepth_surface,site_CP13NOPM,,,
150,D20251102T085245_IFCB199,36.135000,-74.881000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
151,D20251102T091635_IFCB199,36.089000,-74.936000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
152,D20251102T094025_IFCB199,36.044000,-74.995000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
153,D20251102T100414_IFCB199,36.000000,-75.054000,2.13,underway,AR98,IFCB199,,,targetdepth_surface,,,,
154,D20251102T102803_IFCB199,35.956000,-75.112000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
155,D20251102T105153_IFCB199,35.951000,-75.119000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
156,D20251102T111543_IFCB199,35.951000,-75.119000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
157,D20251102T113933_IFCB199,35.951000,-75.119000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
158,D20251102T122206_IFCB199,35.951000,-75.119000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
159,D20251102T124556_IFCB199,35.951000,-75.119000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
160,D20251102T130946_IFCB199,35.952000,-75.120000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
161,D20251102T133336_IFCB199,35.951000,-75.120000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
162,D20251102T135727_IFCB199,35.950000,-75.119000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
163,D20251102T142117_IFCB199,35.950000,-75.119000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
164,D20251102T144507_IFCB199,35.950000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
165,D20251102T150857_IFCB199,35.952000,-75.126000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
166,D20251102T153248_IFCB199,35.945000,-75.128000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
167,D20251102T155638_IFCB199,35.946000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
168,D20251102T162028_IFCB199,35.946000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
169,D20251102T164418_IFCB199,35.946000,-75.125000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
170,D20251103T054053_IFCB199,35.952000,-75.123000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
171,D20251103T060444_IFCB199,35.952000,-75.123000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
172,D20251103T062834_IFCB199,35.952000,-75.123000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
173,D20251103T065224_IFCB199,35.952000,-75.123000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
174,D20251103T071614_IFCB199,35.951000,-75.124000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
175,D20251103T074025_IFCB199,35.952000,-75.124000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,
176,D20251103T080416_IFCB199,35.951000,-75.123000,2.13,underway,AR98,IFCB199,,site_CP10CNSM,targetdepth_surface,site_CP12CNSW,,,

In [62]:
timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
output_filename = f"Metadata_CSVs/{cruise}_shipboard_ifcb_dashboard_metadata_{timestamp}.csv"
metadata_df.to_csv(output_filename, index=False)